# Generated by Django 3.2.6 on 2021-09-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210903_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.CharField(max_length=1000),
        ),
    ]
