# Generated by Django 3.2.6 on 2021-09-07 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210903_1920'),
        ('movies', '0006_alter_rating_comment'),
    ]

    operations = [
    ]
