# Generated by Django 3.2.6 on 2021-09-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rating_comment'),
        ('movies', '0007_merge_20210907_1707'),
    ]

    operations = [
    ]
